mysql:  
  host: localhost
  port: 3306
  database: TikTokLite
  username: user
  password: 123
minio:
  host: localhost
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  videobuckets: video
  picbuckets: pic
  #是否部署在wsl上，不是填fasle即可
  iswsl: true 
  #windows本机ip，视频地址为windows host:port
  winhost: localhost
videofile: ../file/video/
logfile: ../file/log/
picfile: ../file/picture/