mysql:  
  host: 127.0.0.1
  port: 3306
  database: TikTokLite
  username: root
  password: 991229
minio:
  #minio服务主机ip，需要填具体ip
  host: 192.168.10.138
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  videobuckets: video
  picbuckets: pic
  #是否部署在wsl上，不是填fasle即可
  iswsl: false 
  #windows本机ip，视频地址为windows host:port
  winhost: 192.168.1.12
videofile: /tmp/file/video/
logfile: /tmp/file/log/
picfile: /tmp/file/picture/