version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    volumes:
      - "./TikTokLite.sql:/docker-entrypoint-initdb.d/1_TikTokLite.sql"
    environment:
      - MYSQL_DATABASE=TikTokLite
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes" 
  minio:
    image: 'minio/minio:latest'
    ports:
      - 9000:9000
    volumes:
      - "/data/minio:/data/minio"
    command: "server /data/minio"
  redis:
    image: 'redis'
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: "redis-server /etc/redis/redis.conf"
  tiktoklite:
    build: 
      context: .
      dockerfile : ./Dockerfile
    ports:
     - "8080:8080"
    depends_on:
      - mysql
      - minio
      - redis